apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mp-telegram-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mp-telegram-bot
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: mp-telegram-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.telegram.secretName }}
                  key: TELEGRAM_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: uri
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]

